---
title: "Cross Plot Blot Data"
author: "Douglas A. Campbell"
date: "`r format(Sys.Date())`"
output: html_notebook
---
This .Rmd RNotebook imports a tidied data from a .Rds saved from GreenEdgeProtein.Rmd 

```{r set project variables}
Project <- "GreenEdge"
DataIn <- "RawData"
PlotsPath <- "Plots"
DataOut <- "ProcessData"
ProteinTargets <- c("PsbA", "RbcL", "FtsH", "Fcp6", "Lhcx6")
#Fcp6 is standardized using a pseudo Phaedactyum t. std. units = ug not fmole.  This workbook assumes unit is fmole for this target.

FileEncode <- "UTF-8" 
Delimiter <- ","
#this is brittle; better to figure out how to read all data starting at line that contains a key character string
HeaderRows <- 1

#FlagRange is 10% of standard range for flagging estimates outside standard range.
FlagRange <- 0.1

```

```{r load libraries} 
# libraries; Note check actual dependencies
library(tidyverse)
library(lubridate)
library(stringr)
library(broom)
library(knitr)
library(minpack.lm)
library(nlstools)
library(nlsMicrobio)
library(readxl)
#library(googledrive)
#library(googlesheets4)
```
```{r import tidy data}
TidyBlotData <- readRDS(file = file.path(DataOut, "GreenEdge_TargetProteinReport_.Rds"))
```

```{r wider data by target}
WiderData <- TidyBlotData %>%
  pivot_wider(id_cols = c(Sample, Date, Growth_uE, Chla_ug_L,Carbon_ug_mL, N_ug_mL,TotalProtein_ug_mLHarvest, Flag), names_from = Target, values_from = fmol_mL)
```

```{r RbcLPsbAPlot}
RbcLPsbAPlot <- WiderData %>%
  ggplot() +
  geom_point(aes(x = PsbA, y = RbcL, colour = as.factor(Flag))) +
  geom_smooth(aes(x = PsbA, y = RbcL)) +
  theme_bw()

RbcLPsbAPlot
```
```{r FtsHPsbAPlot}
FtsHPsbAPlot <- WiderData %>%
  ggplot() +
  geom_point(aes(x = PsbA, y = FtsH, colour = as.factor(Flag))) +
  geom_smooth(aes(x = PsbA, y = FtsH)) +
  theme_bw()

FtsHPsbAPlot
```
```{r RbcLPsbAuEPlot}
RbcLPsbAuEPlot <- WiderData %>%
  ggplot() +
  geom_point(aes(x = Growth_uE, y = RbcL/PsbA, colour = as.factor(Flag))) +
  geom_smooth(aes(x = Growth_uE, y = RbcL/PsbA)) +
  theme_bw()

RbcLPsbAuEPlot
```

```{r PsbAFtsHuEPlot}
PsbAFtsHuEPlot <- WiderData %>%
  ggplot() +
  geom_point(aes(x = Growth_uE, y = PsbA/FtsH, colour = as.factor(Flag))) +
  geom_smooth(aes(x = Growth_uE, y = PsbA/FtsH)) +
  theme_bw()

PsbAFtsHuEPlot
```



```{r save reported FtsH plots}
ggsave(filename =file.path(PlotsPath, paste(Project, "RbcLPsbAPlot.png", sep = ""),fsep = .Platform$file.sep), device = "png", plot = RbcLPsbAPlot)

ggsave(filename =file.path(PlotsPath, paste(Project, "FtsHPsbAPlot.png", sep = ""),fsep = .Platform$file.sep), device = "png", plot = FtsHPsbAPlot)

ggsave(filename =file.path(PlotsPath, paste(Project, "RbcLPsbAuEPlot.png", sep = ""),fsep = .Platform$file.sep), device = "png", plot = RbcLPsbAuEPlot)

ggsave(filename =file.path(PlotsPath, paste(Project, "PsbAFtsHuEPlot.png", sep = ""),fsep = .Platform$file.sep), device = "png", plot = PsbAFtsHuEPlot)

```

